### ISSUE TITLE
http default protocol for URL argument

### ISSUE THREAD

**Issue by larshelge** [node-modules/urllib#155]
Suggestion: Could we have "http" being default protocol if none is specified in the URL argument. Several libraries (curl, postman) follow this convention.

urllib.request('www.server.com');

Example: URL "www.server.com" will be rewritten as "http://www.server.com" since no protocol is specified.

**Comment by fengmk2** [comment]
Nick suggestion, can you send a pr to improve this?

**Comment by fengmk2** [comment]
@larshelge see #163
