### ISSUE TITLE
Support http2

### ISSUE THREAD

**Issue by fengmk2** [node-modules/urllib#232]
https://github.com/molnarg/node-http2

**Comment by fengmk2** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/http2.html

Landed http2 support and release v3.0.0

**Comment by paambaati** [comment]
@fengmk2 Is there something I can help with?

**Comment by paambaati** [comment]
@fengmk2 Is there some specific task you're looking for? I looked for any current development branches but I couldn't find any.

**Comment by ccwenlin** [comment]
Is this play carry on ?

**Comment by tong3jie** [comment]
3.0版本支持http2？

**Comment by fengmk2** [comment]
528e093c4bbd215167350081f81a49f965f4f6a7
