### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by sparebytes** [node-modules/urllib#255]
I wrote custom typescript definitions for this library so I'm posting it here. If I have time later and the project maintainers wish, I can create a pull request with the definitions.

https://gist.github.com/sparebytes/2b655c1f0939cd7c4ec0c0420cc537b7

**Comment by fengmk2** [comment]
@sparebytes very nice if you can put the definitions into urllib.

**Comment by SoraYama** [comment]
@fengmk2 emmm, actually I've create a typing [package](https://www.npmjs.com/package/@types/urllib) and published on MS [DefinitelyTyped Repo](https://github.com/DefinitelyTyped/DefinitelyTyped). If it can helps I'll be very glad :)

**Comment by fengmk2** [comment]
528e093c4bbd215167350081f81a49f965f4f6a7
