### ISSUE TITLE
上传文件不成功

### ISSUE THREAD

**Issue by sapolang** [node-modules/urllib#257]
const form = formstream();
// form.field('type', 'image');
// form.field('access_token', token);
form.stream('media', fs.createReadStream('./a.jpeg'), 'a.jpeg');

urllib.request(url, {
  method: 'POST',
  headers: form.headers(),
  stream: form,
}, function (err, data, res) {
    console.log(err, data);
});

一直报 ResponseTimeoutError: Response timeout for 5000ms的错误，设置timeout也不行， 文件很小根文件大小无关

**Comment by jemygraw** [comment]
how to solve this problem?
