### ISSUE TITLE
new require('proxy-agent')(proxy) is probably not what you want

### ISSUE THREAD

**Issue by mingyuan-xia** [node-modules/urllib#268]
urllib/lib/detect_proxy_agent.js Line 24:
```
proxyAgent = proxyAgents[proxy] = new require('proxy-agent')(proxy);
```

> It should be new (require('proxy-agent'))(proxy).

> new require('proxy-agent')(proxy) is equal to x = new require('proxy-agent'); x(proxy) and that probably not what you want.

see https://github.com/webpack/webpack/issues/5860#issuecomment-338204689

**Comment by nick-ng** [comment]
I've made a pull request with this change. #273
