### ISSUE TITLE
set 'contentType: "application/json"' did not work?

### ISSUE THREAD

**Issue by ckaaaa** [node-modules/urllib#269]
I use jQuery to send data,like:
var data = {a:1}
$.ajax({url:'http://host/endorsement/surrender',data:JSON.stringify(data),contentType:'application/json',type:'POST'});
It's ok.

And use urllib to send data, like:
urllib.request('http://host/endorsement/surrender', {
        content : JSON.stringify(data),
        method: 'POST',
        contentType:'application/json'
    });
Or
urllib.request('http://host/endorsement/surrender', {
        content : data,
        method: 'POST',
        contentType:'application/json'
    });
Or
urllib.request('http://host/endorsement/surrender', {
        data: JSON.stringify(data),
        method: 'POST',
        contentType:'application/json'
    });
Or
urllib.request('http://host/endorsement/surrender', {
        data: data,
        method: 'POST',
        contentType:'application/json'
    });
Are all did not work.

But I use:
urllib.request('http://host/endorsement/surrender', {
        content : JSON.stringify(data),
        method: 'POST',
        headers:{
            'content-type': 'application/json'
        }
    });

is ok.
Thanks.

**Comment by isayme** [comment]
Solution: change value of `contentType` from `application/json` to `json`.

This issue should closed. @fengmk2
