### ISSUE TITLE
Can't resolve 'dns'

### ISSUE THREAD

**Issue by nperriwp** [node-modules/urllib#278]
When I try to import urllib in my react code, I get the following compile error:

Failed to compile.

./~/socks-proxy-agent/index.js
Module not found: Can't resolve 'dns' in 'C:\ ... \node_modules\socks-proxy-agent'

**Comment by denghongcai** [comment]
urllib is designed to use in node environment, not browser.

you can try https://github.com/matthew-andrews/isomorphic-fetch
