### ISSUE TITLE
contentType 被写死了

### ISSUE THREAD

**Issue by shepherdwind** [node-modules/urllib#281]
https://github.com/node-modules/urllib/blob/0036c0d4fa53f03600f4947520bf473c5ce63f00/lib/urllib.js#L323-L332
我这边有一个这样的接口

> 通讯双方采用http post方法作为通讯协议。请求头必须添加： "Content-type","application/x-www-form-urlencoded;charset=XXX charset:GBK,UTF-8 可选

没法搞了，这里可以开放允许用户自定义 context-type 么？

**Comment by orangemi** [comment]
Request Headers is overwritten here:
https://github.com/node-modules/urllib/blob/0036c0d4fa53f03600f4947520bf473c5ce63f00/lib/urllib.js#L281-L285

Try this:

```js
urllib.request('http://example.com', {
  headers: {
    'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
  },
  data: 'a=b&c=d'
})
```
