### ISSUE TITLE
不支持cookie？

### ISSUE THREAD

**Issue by yuzai** [node-modules/urllib#299]

**Comment by fengmk2** [comment]
Please use `Cookie` headers.

**Comment by yuzai** [comment]
我是说我发送请求之后，服务端返回set-cookie，这里不会自动帮忙处理掉？

**Comment by fengmk2** [comment]
不会处理。

**Comment by yuzai** [comment]
嗯，仔细想了下，其实自己处理更合理，之前用request，会自动帮忙做一部分处理，但是作用并不大，有时候需要带cookie，有时候又不需要带，自己操作空间更大一点。
ps: egg还是挺好用的

**Comment by Jeff-Tian** [comment]
> Cookie Header这个没有文档呀！

一个 `TypeScript` 例子，亲测有效

```typescript
import {request} from 'urllib'

request('https://example.com', {
  method: 'POST',
  headers: {
    'cookie': 'EGG_SESS=1234'
  }
})
```

**Comment by atian25** [comment]
> Cookie Header这个没有文档呀！

MDN 文档，谢谢。

**Comment by crazy4groovy** [comment]
Does this lib support auto cookie parsing and sending, like request's `jar`?
https://www.npmjs.com/package/request#requestoptions-callback
