### ISSUE TITLE
正在上传文件过程中断网，有时候无法触发回调，也没有报错，希望能关注一下

### ISSUE THREAD

**Issue by panshangqi** [node-modules/urllib#311]
urllib.js  abortRequest（）函数 最后一行req.abort() 加上done(__err), ，可以暂时解决这个问题，希望能有所改善

**Comment by fengmk2** [comment]
@panshangqi 你的 node 版本是多少？https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L924 这里有特殊判断，socket 没有创建之前会主动调用 done。否则会等 req.abort() 来触发 req 的 error 事件 https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L1038

**Comment by panshangqi** [comment]
@fengmk2  版本号：urllib@2.31.2
