### ISSUE TITLE
上传文件异常

### ISSUE THREAD

**Issue by sophister** [node-modules/urllib#323]
hi，最近在使用这个库的时候，请求微信的API上传图片，总是失败。
请求的是微信这个接口：[https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.uploadTempMedia.html](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.uploadTempMedia.html)

下午换成 `request` 库，就没问题了，不知道是不是使用方式不对……

**Comment by whxaxes** [comment]
请求的 options 加个 rejectUnauthorized: false ，urllib 默认会进行证书校验，微信开放接口的证书估计是是自己签的，所以通不过校验

**Comment by sophister** [comment]
应该不是https证书问题，请求确实可以发过去，但是有好几种问题。有的是微信没法收到上传的图片；一种是直接返回 `503` 服务器错误。大概代码是这样的： 

```javascript
urllib.request(url, {
             method: 'post',
             files: {
                     media: fs.createReadStream('xxxx')
            },
});
```
