### ISSUE TITLE
请问怎么发送二进制数据？

### ISSUE THREAD

**Issue by bymaxchen** [node-modules/urllib#329]
`      
const { data } = yield ctx.curl(`${url}/?seq=${seq}&end=${end}`, {
        method: 'POST',
        dataType: 'json',
        content: string,
        headers: {
          'content-type': 'application/octet-stream',}, 
       });
`

content是二进制字符串，但是发过去内容就不对了。是因为编码的原因吗？

**Comment by atian25** [comment]
content: buffer

**Comment by bymaxchen** [comment]
> `content: Buffer.from(string)`

谢了。但是二进制的话，还需要加上编码。

Buffer.from(string, 'binary')
