### ISSUE TITLE
How could I change filename using buffer uplopd with Multipart case in urllib?

### ISSUE THREAD

**Issue by releasethecow** [node-modules/urllib#332]
How could I change filename using buffer uplopd with Multipart case in urllib?

see request data:
![image](https://user-images.githubusercontent.com/7903541/68387809-2aa0e400-019a-11ea-91dc-8c9692061240.png)

As I could see https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L375
I may NOT be able to do that.

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, please rovide a mini project and upload to your GitHub.

**Comment by releasethecow** [comment]
@atian25 Hi, the case is happen when I try to send  multipart data, using file type `Buffer` in egg js `curl`

```js
// fileUpload.js
const bitmap = Buffer.from(imgBase64, 'base64'); // imgBase64 is string of base64 image
const response = await ctx.curl('http://this.is.a.file.server.com/upload/some/service', {
  method: 'POST',
  dataType: 'json',
  headers: {
    'content-disposition': 'form-data;name="foo";filename="foo.jpg"',
  },
  data: {
    requestId: '12345678',
    // ... more part of http request
  },
  // single file upload
  files: bitmap, // this make 'content-type': 'multipart/form-data'
});
```

As I could see in `http://this.is.a.file.server.com`, I can see the final http request, the final part "file" in screenshot above, only "bufferfile0" is found as filename. 

that make sense because I was trying to upload base64 but NOT a file.
in this case, urllib helps to make default filename as `bufferfile${index}`, so my file has been rename to 'bufferfile0'. see https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L375

but my requirement is asking you, if I could this case, and set the http part 'content-disposition' (NOT the http post headers by curl itself)in any extension? like:

```js
// fileUpload.js
const bitmap = Buffer.from(imgBase64, 'base64'); // imgBase64 is string of base64 image
const response = await ctx.curl('http://this.is.a.file.server.com/upload/some/service', {
  // ...
  files: bitmap, // this make 'content-type': 'multipart/form-data'
  fileHeaders: { // I may need some extension like this to set part data
    'content-disposition': 'form-data;filename="foo.jpg"'
  }
});
```

![image](https://user-images.githubusercontent.com/7903541/68453930-f11bb780-0231-11ea-97dd-47b8585bf56d.png)

pls let me know if I my question is clear enough. thx.

**Comment by atian25** [comment]
try formstream ？

https://github.com/node-modules/urllib#options-optionsstream

**Comment by releasethecow** [comment]
@atian25 I agree that should be the best choice. but `http://this.is.a.file.server.com` is not friendly enough with stream :)

anyway, I will try to push the file server to enhance this.

**Comment by atian25** [comment]
formstream is just a module to config multipart, it's content-type is still form-data.

`form.buffer('file2', new Buffer('This is file2 content.'), 'foo.txt');`

**Comment by releasethecow** [comment]
I see. thanks a lot!
