### ISSUE TITLE
请问如何发起multipart/form-data; boundary=----类型的请求传参

### ISSUE THREAD

**Issue by hnty545** [node-modules/urllib#333]
"egg": "^2.23.0"应该是内置urllib来当httpclient，后台有个登录接口需要用multipart/form-data来传字符串的参数。。
在浏览器版本我用axios，谷歌浏览器内置了FormData对象来传参，可以正常调用接口
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryGA51mBNJvYGa6cMn
![image](https://user-images.githubusercontent.com/6417805/69130097-e216ee00-0aea-11ea-9865-1f4c828f68b9.png)

现在用node做bff使用egg来实现，我弄了好久不知道怎么实现，请给我些建议，谢谢！

**Comment by atian25** [comment]
没啥区别啊，urllib 怎么用就怎么用，只是不需要你 new 一个 urllib 而已，传递对应的 options 就好了。

**Comment by atian25** [comment]
多看文档：
- https://eggjs.org/zh-cn/core/httpclient.html#form-%E8%A1%A8%E5%8D%95%E6%8F%90%E4%BA%A4
- https://eggjs.github.io/zh/guide/httpclient.html#%E6%8F%90%E4%BA%A4-form-%E8%A1%A8%E5%8D%95

**Comment by hnty545** [comment]
@atian25 我看了这部分文档的
现在我是这样做
options中dataType: 'json',
使用了这个库form-data

postApi(
    apiName,
    url,
    data = null,
    options = {
      headers: null,
      dataType: 'json',
      timeout: 10000,
      allowEmpty: false,
      timing: false
    }
  ) {
    let formData = null;
    if (data) {
      formData = new FormData();
      for (let [k, v] of Object.entries(data)) {
        formData.append(k, v);
      }
    }
    let headers = null;
    if (formData) {
      headers = {
        ...options.headers,
        ...formData.getHeaders()
      };
    } else {
      headers = options.headers;
    }
    return this._requestApi({
      ...options,
      apiName,
      url,
      method: 'POST',
      odata: JSON.stringify(data),
      data: formData,
      headers: headers
    });
  }

但是服务端拿不到参数

**Comment by atian25** [comment]
这代码怎么看。。。 学下 Markdown 的排版。

看 urllib 的单测示例，还有 egg 的单测示例自行分析吧。

如果还有问题，提交最小可复现代码库。

**Comment by hnty545** [comment]
我这个情况可能比较特殊
application/x-www-form-urlencoded 
后台拿不到参数

浏览器中headers是
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryGA51mBNJvYGa6cMn

Form Data是这样

------WebKitFormBoundaryGA51mBNJvYGa6cMn
Content-Disposition: form-data; name="action"

login
------WebKitFormBoundaryGA51mBNJvYGa6cMn
Content-Disposition: form-data; name="userName"

CS0000001
------WebKitFormBoundaryGA51mBNJvYGa6cMn
Content-Disposition: form-data; name="password"

24a057a659ce5b04762f9a1f93a95ad6
------WebKitFormBoundaryGA51mBNJvYGa6cMn--

**Comment by hnty545** [comment]
请问代码怎么传给你呢

**Comment by atian25** [comment]
先理清楚你的问题吧。。。 感觉跟 egg 没啥关系，你现在是用 urllib 发送 form 请求这块都没搞明白。

先这个搞明白，然后才是在 egg 里面用 httpclient（urllib）请求另一个服务如何处理。

代码自然是提交到自己的 GitHub 仓库啦，注意，是最小可复现代码，不要一大坨。

**Comment by hnty545** [comment]
egg是内部用的urllib，所以我提交到这儿来了

**Comment by hnty545** [comment]
我看到urllib要不是发application/x-www-form-urlencoded
而multipart/form-data是针对文件的，在options中传files，但是只支持传文件
这些我都看过的

**Comment by atian25** [comment]
https://github.com/node-modules/urllib#options-optionsstream

**Comment by hnty545** [comment]
哦要用这个库吗，感谢
我试试看

**Comment by hnty545** [comment]
postApi(
    apiName,
    url,
    data = null,
    options = {
      headers: null,
      dataType: 'json',
      timeout: 10000,
      allowEmpty: false,
      timing: false
    }
  ) {
    let formData = null;
    if (data) {
      formData = new formstream();
      for (let [k, v] of Object.entries(data)) {
        formData.field(k, v);
      }
    }
    let headers = null;
    if (formData) {
      headers = {
        ...options.headers,
        ...formData.headers()
      };
    } else {
      headers = options.headers;
    }
    return this._requestApi({
      ...options,
      apiName,
      url,
      method: 'POST',
      odata: JSON.stringify(data),
      stream: formData,
      headers: headers
    });
  }

我按这个例子改了，后台还是拿不到参数

**Comment by hnty545** [comment]
@atian25 我还是把项目传到仓库吧，帮忙看看，谢谢了

**Comment by hnty545** [comment]
@atian25 https://github.com/hnty545/node-bff/invitations

**Comment by hnty545** [comment]
谢谢

**Comment by hnty545** [comment]
用这个来启动，npm run dev，dubbo的接口是内网的不管
用这个地址访问调试窗口，http://127.0.0.1:18080/graphql
测试代码我发给你QQ邮箱，谢谢了！

**Comment by atian25** [comment]
最小化代码的意思是，用 `npm init egg --type=simple` 创建一个最小的可复现方式，那么一大坨代码没法看的。

**Comment by hnty545** [comment]
就在plugin/http/HttpClient.js
这个工程得跑起来才能调试的，代码并不复杂，主要是没办法达到H5版本那样直接成功的访问后台接口，也就是登录接口
用node去访问，在egg里是urllib，总是拿不到参数

**Comment by hnty545** [comment]
已经解决了，客户端是你说的那样写没问题的，是另外一个小问题，谢谢了
