### ISSUE TITLE
以表单方式提交 multipart 是不是存在问题

### ISSUE THREAD

**Issue by jsjett** [node-modules/urllib#358]
![image](https://user-images.githubusercontent.com/58426583/115398709-04e68e00-a21a-11eb-8673-e63ced5b1777.png)
 
后端需要接口是需要 如下数据

{
  a: 1,
  data: fs.readFileSync('./sss.jpg')
}

查看urllib才发现最后是把这个对象变成了流发送出去 后端根本拿不到这个文件的data

而采用 superagent 就可以了 

`
  superagent.put('http://www.baidu.com/upload')
.field('a', 1)
.attach('data', buff)
 .then(res => {
    console.log(res)
})
`

所以 urllib 的 formData是不是有点问题

**Comment by atian25** [comment]
没问题，应该是使用不当，可以自己抓包对比下 header 和 body
