### ISSUE TITLE
Remove utility to reduce package size

### ISSUE THREAD

**Issue by jimmywarting** [node-modules/urllib#362]
This two can easily be replaced with `Object.assign({}, ...)` or with spread `{ ... }`
https://github.com/node-modules/urllib/blob/f2a42d19d2236979c16eea13c229839e5a78b381/lib/httpclient.js#L40
https://github.com/node-modules/urllib/blob/f2a42d19d2236979c16eea13c229839e5a78b381/lib/httpclient.js#L51

Here you can use `Object.keys()`
https://github.com/node-modules/urllib/blob/04734a13e146da501f4e38333d5de9f9bbb259d1/lib/urllib.js#L309

**Comment by fengmk2** [comment]
Pull request is welcome

**Comment by TommyDew42** [comment]
Hi! Can I take this up?

**Comment by atian25** [comment]
sure
