### ISSUE TITLE
自动把只有一项的数组参数转为字符串

### ISSUE THREAD

**Issue by xiangyuisabatman** [node-modules/urllib#364]
当我将dataType设置成json，传参数的时候，如果参数a:['a']只有一项，就会自动转成a: ‘a’，数组结构就没了。这个算bug吗，还是设计如此。

**Comment by atian25** [comment]
提供最小可复现代码库

**Comment by fengmk2** [comment]
dataType 是描述 response 如何处理的，你需要设置 contentType 为 json，它是描述 request 的。
