### ISSUE TITLE
The version number needs to be modified, and the old node is no longer available

### ISSUE THREAD

**Issue by starmooms** [node-modules/urllib#376]
Installation failed on `node@8.9.3` 

```
yarn add urllib

yarn add v1.21.1
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
error socks@2.6.1: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.9.3"
error Found incompatible module.
```
This may be because 

[`fix: upgrade proxy-agent to fix the security vulnerability`](https://github.com/node-modules/urllib/pull/368)

Cause breakthrough change

Our old project use `ali-oss@^4.6.3` on `node@8.9.3`,  dependencies `urllib@^2.17.1`

Due to the wrong version number, it cannot be used when updating as a module

```
yarn add ali-oss@^4.6.3

yarn add v1.21.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error socks@2.6.1: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.9.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.


## can ignore the engine to view the 'yarn.lock' dependency
# yarn add ali-oss@^4.6.3 --ignore-engines

```

Therefore, you may need to republish it twice. The repaired `2.*.*` can be used, and the new `3.*.*` can be published

**Comment by fengmk2** [comment]
cc @hyj1991

**Comment by fengmk2** [comment]
@starmooms node v8 is no more LTS support, can you upgrade node to 10 or 12?

**Comment by hyj1991** [comment]
Hi, `urllib` no longer support non-lts version, please upgrade your nodejs :)

**Comment by starmooms** [comment]
We rely on `ali-oss@^4.6.3` in a public module. The upgrade may involve other projects and can only be used for the time being `ali-oss@4.4.3`.

I think as a basic dependency, there should be good version number management, which may involve many other projects. But the version number may have been confused (#316)

Anyway, thank you for you reply. This in can be closed

**Comment by fengmk2** [comment]
https://github.com/TooTallNate/node-proxy-agent/blob/master/package.json#L10 proxy-agent support node@8
