### ISSUE TITLE
digestAuth property missing in RequestOptions

### ISSUE THREAD

**Issue by marek-benes** [node-modules/urllib#388]
Starting from version 3 digestAuth property missing in RequestOptions type. Is Digest auth still supported?

**Comment by fengmk2** [comment]
digestAuth Will support in v3, working in progress.

**Comment by marek-benes** [comment]
When do you plan to publish a new version with digest auth support, please?

**Comment by fengmk2** [comment]
@marek-benes latest version is support digest auth
