### ISSUE TITLE
Cannot find module 'diagnostics_channel' on urllib 3.2.0

### ISSUE THREAD

**Issue by kyleinfo** [node-modules/urllib#401]
urllib@3.1.3 is ok, but 3.2.0 get this error:  "errorMessage": "Cannot find module 'diagnostics_channel'
![image](https://user-images.githubusercontent.com/7193422/192194257-f45a425a-c18c-4616-9471-d43fe4ed19e3.png)

**Comment by fengmk2** [comment]
Please use Node.js >=14.17.0
