### ISSUE TITLE
build error: Cannot find name 'Lowercase'.

### ISSUE THREAD

**Issue by into-piece** [node-modules/urllib#411]
```
node_modules/_urllib@2.39.0@urllib/lib/index.d.ts:15:25 - error TS2304: Cannot find name 'Lowercase'.
15 method?: HttpMethod | Lowercase<HttpMethod>;
~~~~~~~~~
Found 1 error.
```
![image](https://user-images.githubusercontent.com/23183463/194735872-36f686cc-9ff7-42c2-9f66-ce62b0d87853.png)
urllib version: @2.39.0
node version: v6.16.0

**Comment by fengmk2** [comment]
closes by 01b54a9fa48bdd745798fd06ad32ed41f22815d3

**Comment by fengmk2** [comment]
+ urllib@2.39.1

**Comment by fengmk2** [comment]
https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#lowercasestringtype
