### ISSUE TITLE
diagnostics_channel should be a dependency in version 3.3.1

### ISSUE THREAD

**Issue by WJayWJay** [node-modules/urllib#414]
Error: Cannot find module 'diagnostics_channel'

![image](https://user-images.githubusercontent.com/3736332/196839573-98acac97-2d66-40f0-8ef3-207f195804bc.png)

**Comment by WJayWJay** [comment]
maybe u should add a test case to check it!

**Comment by hyj1991** [comment]
The `diagnostics_channel ` is a built-in module which added in node-v14.x, and urllib@3 needs node version >=14.17.0 :)

See: https://github.com/node-modules/urllib/blob/master/package.json#L87-L89
