### ISSUE TITLE
timeout mechanism does not make sense for big request/response

### ISSUE THREAD

**Issue by zensh** [node-modules/urllib#59]
Timeout should be determined by socket event

**Comment by fengmk2** [comment]
Can you show me more details?

**Comment by zensh** [comment]
目前的 timeout 机制是“死的”，比如上传或下载大文件，我必须要根据文件大小和网络带宽调整 timeout 值，实际上网络状况还是浮动变化的，我无法设置一个合理的 timeout 值。 
理想的 timeout 机制应该根据数据帧来判断：对于一个连接，当超过一定时间没有接收到数据帧时，才认为 timeout

**Comment by fengmk2** [comment]
下载直接 stream 模式，timeout 只管拿到 header 的过程。

上传的话得考虑考虑。

**Comment by fengmk2** [comment]
@zensh 可以提个 pr 改善 timeout 机制？

**Comment by zensh** [comment]
都忘了这事，周末研究下

**Comment by zensh** [comment]
其实 http request 有 timeout，本质上也是 socket 的 timeout ：
https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback
https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback

但是与现有的 timeout option 概念上有区别，改成 node 自带的 settimeout 机制会不会带来其它影响？

**Comment by fengmk2** [comment]
自带那个timeout不会像预期那样工作的，特别是在云环境下

**Comment by zensh** [comment]
那暂时应该是没有合适的解决方案了 :8ball:

**Comment by fengmk2** [comment]
http://mongodb.github.io/node-mongodb-native/2.1/reference/faq/ 这里讲到的 socketTimeout 其实很难保证在所有环境生效。
