### ISSUE TITLE
Api not friendly

### ISSUE THREAD

**Issue by shepherdwind** [node-modules/urllib#64]
Only on method

* http.request(url[, options][, callback])

But the options object is so big, That is very hard to config.

I think superagent provide api will more firendly.

**Comment by fengmk2** [comment]
@shepherdwind pr welcome :)

**Comment by fengmk2** [comment]
@shepherdwind also invite you to join https://github.com/node-modules group.

**Comment by shepherdwind** [comment]
⊙﹏⊙b, So I have to do some thing now. I just almost forget this.
