### ISSUE TITLE
how to post xml data

### ISSUE THREAD

**Issue by zhangda89** [node-modules/urllib#69]
how to post xml data

**Comment by fengmk2** [comment]
`content`: xml-string, and `contentType`: `'application/xml'`

**Comment by Jeff-Tian** [comment]
> `content`: xml-string, and `contentType`: `'application/xml'`

Actually the `contentType: 'application/xml'` does not pass through to the final http request headers. So created a PR: https://github.com/node-modules/urllib/pull/325, please kindly help review.
