### ISSUE TITLE
when will data in callback function be undefined?

### ISSUE THREAD

**Issue by kyfxbl** [node-modules/urllib#70]
```js
urllib.request(url, options, function(err, body, resp){

        if(err){
            callback(err);
            return;
        }

        if(body.errcode){
            callback(body);
            return;
        }

        // logic
    });
```

we found body is undefined while err is null (means no error happend), then program crash because of "Cannot read property 'errcode' of null"

**Comment by fengmk2** [comment]
@kyfxbl Are you using `args.streaming = true` or `args.writeStream`?

- streaming: https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L449
- writeStream: https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L491
