### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by zhangda89** [node-modules/urllib#72]
self signed certificate in certificate chain
这个问题要如何处理

**Comment by fengmk2** [comment]
https://nodejs.org/api/https.html#https_https_request_options_callback

> rejectUnauthorized: If true, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails. Verification happens at the connection level, before the HTTP request is sent. Default true.

set `rejectUnauthorized: false`

**Comment by JordanDC2** [comment]
It looks as though `rejectUnauthorized` does not exist on the `RequestOptions` interface. Is there a way of allowing self-signed certificates currently?
