### ISSUE TITLE
how to send https request with a .p12 certificate?

### ISSUE THREAD

**Issue by kyfxbl** [node-modules/urllib#74]
hello, my code is:
```
var url = "https://api.mch.weixin.qq.com/mmpaymkttransfers/sendredpack";

var options = {
    method: "POST",
    data: content,
    dataType: "text",
    pfx: p12_path,
    passphrase: params.mch_id,
    ca: ca_path,
    rejectUnauthorized: true
};

urllib.request(url, options, callback);
```

p12_path is .p12 file path, and params.mch_id is the password of the .p12 file

it seems not work

thanks very much

**Comment by fengmk2** [comment]
urllib just pass `pfx`, `passphrase`, `ca` to https.request https://iojs.org/api/https.html#https_https_request_options_callback
